<?php

	$blog_posts = array(
	
		(object) array(
			"title" => "Cirro Hires New Employee!",
			"body" => "Bitterleaf potato azuki bean catsear epazote bok choy tatsoi lettuce nori. Sierra leone bologi kohlrabi napa cabbage caulie squash tatsoi welsh onion avocado chickweed. Burdock amaranth tigernut garlic celery spinach maize bitterleaf mustard quandong celery parsley garbanzo bell pepper asparagus. Plantain dandelion prairie turnip pea corn shallot carrot seakale pea sprouts onion cucumber bush tomato leek maize. Grape groundnut kohlrabi water spinach courgette prairie turnip.",
		),
		
		(object) array(
			"title" => "I love to read about computers!",
			"body" => "Ham salami hamburger sausage shoulder pancetta kielbasa biltong chicken frankfurter. Jowl brisket ham hock, frankfurter biltong pancetta chicken sirloin short loin pork chop tongue short ribs bacon drumstick tail. T-bone ribeye short loin turkey shoulder rump beef ribs chicken boudin sirloin bresaola kielbasa pork chop capicola. T-bone capicola flank, pork belly fatback ham hock brisket salami chicken frankfurter ground round corned beef. Leberkas turkey salami beef tri-tip filet mignon, turducken swine ham hock chuck boudin flank fatback bacon capicola. Filet mignon tongue spare ribs meatball tri-tip. Sausage shankle ground round leberkas andouille biltong.",
		),
		
		(object) array(
			"title" => "Just another blog post",
			"body" => "Strip steak venison pancetta ball tip flank ham hock chicken. Bresaola cow chicken jowl pork boudin turducken. Pork shankle meatloaf turkey jerky ball tip tail beef ribs pork belly shank salami pastrami. Shank hamburger pig tenderloin pastrami salami. Ribeye ground round boudin spare ribs drumstick, prosciutto corned beef andouille brisket tenderloin bresaola jowl hamburger chicken meatloaf. Sausage turkey prosciutto, brisket capicola salami chicken shoulder cow turducken.

Jowl turducken t-bone, pastrami leberkas pork chop chuck biltong pork belly bacon frankfurter. Salami pancetta beef ribs, hamburger short loin beef t-bone tri-tip capicola kielbasa ball tip. Turducken boudin sirloin andouille. Fatback prosciutto filet mignon bacon. Tongue meatloaf corned beef strip steak meatball. Fatback andouille swine tongue. Pork tri-tip turkey, prosciutto biltong venison salami pork loin filet mignon chuck.",
		),
	);
	
	$blog_posts = (object) $blog_posts;